# Generated by Django 5.2.4 on 2025-10-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_types", "0002_alter_documenttype_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttype",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nombre"),
        ),
    ]
