# Generated by Django 5.2.4 on 2025-10-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_types", "0003_alter_documenttype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
    ]
