# Generated by Django 5.2.4 on 2025-10-12 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_types", "0004_alter_paymenttype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentstatus",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de creación",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentstatus",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AddField(
            model_name="paymentstatus",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nombre"
            ),
        ),
        migrations.AlterField(
            model_name="paymentstatus",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descripción"
            ),
        ),
        migrations.AlterField(
            model_name="paymentstatus",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nombre"
            ),
        ),
        migrations.AlterField(
            model_name="paymenttype",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Eliminacion"
            ),
        ),
        migrations.AlterField(
            model_name="paymenttype",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nombre"
            ),
        ),
    ]
